### ISSUE TITLE
cloudflare保护的网站，访问异常

### ISSUE THREAD

**Issue by iikira** [JclMiku/TBsign#3]
尤其是https

**Comment by JclMiku** [comment]
麻烦描述的详细一点

**Comment by iikira** [comment]
怎么说呢，cf cdn启用https，浏览器使用https连接网站，但cf节点代理的仍然是http80端口
所以这样做的后果就是，展示的页面js，css不生效，除非去cf关掉https
我怀疑php $_SERVER得到的参数不准确造成的。

**Comment by U2FsdGVkX1** [comment]
开启https是安装完成之前开启的吗？

**Comment by iikira** [comment]
是的，之前一直开

**Comment by U2FsdGVkX1** [comment]
打开yq_options数据表，找到system_url，把它更改为正确的地址(https地址)

**Comment by iikira** [comment]
好了，以后还是用js获取url吧。另外，作者有没有在做插件？

**Comment by U2FsdGVkX1** [comment]
除了预装的插件，暂时没别的插件。。不过另一个作者 @JclMiku 就有一部分插件，你可以肛他（
